### ISSUE TITLE
Reviewing Python Pull Requests 

### ISSUE THREAD

**Issue by Anahita97** [UBC-MDS/collinearity_tool#29]
- Ana/ Katia
- Nick/ Chaoran

**Comment by katerinkus** [comment]
@nickmao1994 I could not locate your issue for your function so I am writing here. Looks like you are missing `from collinearity_tool.collinearity_tool import <your_function_name>` from the testing file.

**Comment by katerinkus** [comment]
@nickmao1994 I get the following:
```
E       ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().`
    actual = corr_matrix(df_3, decimals = 2)[0]
```

when running this test
`    assert actual == None, "The correlation coefficient matrix should only return None."`

My suggestion is to either remove it or try to fix it using the methods they describe above such as` .empty()`

Also, `numerics` are missing from the src file, so assert statements do not run.
`numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']`

Otherwise, other tests are passing! Hope this helps :)

**Comment by nickmao1994** [comment]
@katerinkus Thanks for pointing this out! I have updated the test code in the recent pr:https://github.com/UBC-MDS/collinearity_tool/pull/35. And from what I have seen on the main branch, `numerics`  are in the src file. It's in line 33.

**Comment by showcy** [comment]
Done
